### PR TITLE
Add google signin

### PR DESCRIPTION
**Pull request by claywjames**
Google sign in should be working.  When we put this code into pythonanywhere, we need to change the instance/config file locally on the server for it to work correctly.

### CODE REVIEW

**Comment by mckennaman123** [comment]
When I try and sign in after running the server locally I get a redirect uri mismatch error, do you know why that would be? Also, on mobile, I think the google sign in button and menu button overlap a little bit. Everything else looks good though!

**Comment by mckennaman123** [comment]
I also noticed an alert pops up (at least for me anyways) whenever I initially go to the site saying "could not sign in".

**Comment by claywjames** [comment]
Are there any errors in the developers console? or on the backend? I'll check it out when we meet up before class

**Comment by mckennaman123** [comment]
I haven't checked on the dev console yet, the backend works fine as far as I've checked.

**Pull request merged**
