### PR TITLE
fix header

### PR DESCRIPTION
**Pull request by claywjames**
I updated the header so that the logo doesn't stretch it out and so that it looks good on mobile.

### CODE REVIEW

**Comment by mckennaman123** [comment]
I like how the logo stands out now. On mobile it looks like the menu button cuts off the google signin button though, and when the menu button is clicked it also cuts off the logo.
screenshot 2018-11-05 00 06 08
screenshot 2018-11-05 00 06 15

**Comment by claywjames** [comment]
when you change the screen size you gotta reload the page.  Sorry I should have mentioned that

**Comment by claywjames** [comment]
The logo should disappear and the sign in stuff should shift to the left

**Comment by mckennaman123** [comment]
Okay, I reloaded it and see that now, cool! The code makes sense now haha, I was a little confused before. Looks good to me

**Comment by claywjames** [comment]
Haha sorry about that!

**Pull request merged**
